Варіант 14

In [8]:
import numpy as np

## Завдання 1

Створіть одновимірний масив (вектор) із геометричною прогресією, де кожне наступне число менше попереднього в 3 рази, починаючи з 81, та виведіть його значення.

In [18]:
first_value = 81
ratio = 1/3
num_elements = 10
geom_progression = [first_value * (ratio ** i) for i in range(num_elements)]

geom_progression


[81.0,
 27.0,
 9.0,
 2.999999999999999,
 0.9999999999999998,
 0.3333333333333332,
 0.11111111111111106,
 0.03703703703703702,
 0.012345679012345673,
 0.004115226337448557]

## Завдання 2

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими значеннями дробових частин від ділення кожного числа на 2, починаючи з 1, та виведіть його значення.

In [21]:
numbers = np.arange(1, 10)
fractional_parts = numbers / 2 - np.floor(numbers / 2)
# Заміна нульових значень на дуже мале значення, щоб уникнути ділення на нуль
fractional_parts[fractional_parts == 0] = np.inf
inverse_values = 1 / fractional_parts
# Перетворюємо одновимірний масив у двовимірний розміром 3x3
matrix = inverse_values.reshape(3, 3)

matrix

array([[2., 0., 2.],
       [0., 2., 0.],
       [2., 0., 2.]])

## Завдання 3

Створіть масив розміром 4x4, заповніть його випадковими натуральними числами від 1 до 10 і знайдіть мін елемент.

In [45]:
matrix = np.random.randint(1, 11, size=(4, 4))
min_element = np.min(matrix)

print(f'   matrix\n', matrix)
print(f"мін. елемент:", min_element)


   matrix
 [[ 8  1  3  9]
 [10  5  1  7]
 [ 9  4  2  3]
 [ 3  6 10 10]]
мін. елемент: 1


## Завдання 4

Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє арифметичне елементів, розташованих на побічній діагоналі.

In [61]:
matrix = np.random.rand(5, 5)
anti_diagonal = np.fliplr(matrix).diagonal()
mean_value = np.mean(anti_diagonal)

print(f'   matrix \n', matrix)
print(f'   anti diagonal \n', anti_diagonal)
print(f'   mean \n', mean_value)


   matrix 
 [[0.6  0.97 0.9  0.48 0.97]
 [0.07 0.42 0.62 0.98 0.47]
 [0.42 0.08 0.63 0.61 0.6 ]
 [0.22 0.14 0.3  0.79 0.29]
 [0.72 0.6  0.95 0.97 0.3 ]]
   anti diagonal 
 [0.97 0.98 0.63 0.14 0.72]
   mean 
 0.6878691443611608


## Завдання 5

Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [108]:
array1 = np.random.randint(1, 21, size=5)
array2 = np.random.randint(1, 21, size=5)

# Поелементні операції
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)


Array 1: [18 19  5  3 17]
Array 2: [ 4  3 11 14 17]
Addition: [22 22 16 17 34]
Subtraction: [ 14  16  -6 -11   0]
Multiplication: [ 72  57  55  42 289]


## Завдання 6

Створіть дві матриці 3x3, заповніть їх довільними цілими числами від -5 до 5 та знайдіть їх добуток.

In [109]:
matrix1 = np.random.randint(-5, 6, size=(3, 3))
matrix2 = np.random.randint(-5, 6, size=(3, 3))
product = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Product of Matrix 1 and Matrix 2:\n", product)

Matrix 1:
 [[ 2  0  4]
 [-5  5 -3]
 [ 5  2 -3]]
Matrix 2:
 [[ 4 -3 -2]
 [-2 -3 -2]
 [-1 -4 -3]]
Product of Matrix 1 and Matrix 2:
 [[  4 -22 -16]
 [-27  12   9]
 [ 19  -9  -5]]


## Завдання 7

Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [106]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 4))

product = np.dot(matrix1, matrix2)

print("Matrix 1 (2x3):\n", matrix1)
print("Matrix 2 (3x4):\n", matrix2)
print("Product of Matrix 1 and Matrix 2 (2x4):\n", product)

Matrix 1 (2x3):
 [[2 2 2]
 [2 4 4]]
Matrix 2 (3x4):
 [[3 4 1 4]
 [5 2 3 5]
 [4 5 5 5]]
Product of Matrix 1 and Matrix 2 (2x4):
 [[24 22 18 28]
 [42 36 34 48]]


## Завдання 8

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю

In [76]:
matrix = np.random.randint(1, 11, size = (3, 3))

inverse_matrix = np.linalg.inv(matrix)

print(f"Matrix:\n{matrix}")
print(f"Inverse matrix:\n{inverse_matrix}")

Matrix:
[[ 9  2  6]
 [10  9 10]
 [ 5  4  1]]
Inverse matrix:
[[ 0.14 -0.1   0.15]
 [-0.17  0.09  0.13]
 [ 0.02  0.11 -0.27]]


## Завдання 9

Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [78]:
matrix = np.random.uniform(0, 1, size = (4, 4))

transposed_matrix = matrix.T

print(f"Matrix:\n{matrix}")
print(f"Transposed matrix:\n{transposed_matrix}")

Matrix:
[[0.57 0.02 0.62 0.61]
 [0.62 0.94 0.68 0.36]
 [0.44 0.7  0.06 0.67]
 [0.67 0.21 0.13 0.32]]
Transposed matrix:
[[0.57 0.62 0.44 0.67]
 [0.02 0.94 0.7  0.21]
 [0.62 0.68 0.06 0.13]
 [0.61 0.36 0.67 0.32]]


## Завдання 10

Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [128]:
matrix = np.random.uniform(0, 1, size = (3, 4))
vector = np.random.randint(0, 1, size = (4, 1))

product_matrix_vector = np.dot(matrix, vector)

print(f"Matrix 3x4:\n{matrix}")
print(f"Vector 4x1:\n{vector}")
print(f"Matrix product by vector:\n{product_matrix_vector}")

Matrix 3x4:
[[0.85 0.5  0.43 0.82]
 [0.74 0.45 0.97 0.36]
 [0.4  0.74 0.45 0.94]]
Vector 4x1:
[[0]
 [0]
 [0]
 [0]]
Matrix product by vector:
[[0.]
 [0.]
 [0.]]


## Завдання 11

Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [100]:
matrix = np.random.randint(0, 1, size = (2, 3))
vector = np.random.uniform(1, 11, size = (3, 1))

product_matrix_vector = np.dot(matrix, vector)

print(f"Matrix 2x3:\n{matrix}")
print(f"Vector 3x1:\n{vector}")
print(f"Matrix product by vector:\n{product_matrix_vector}")

Matrix 2x3:
[[0 0 0]
 [0 0 0]]
Vector 3x1:
[[10.77]
 [ 9.77]
 [ 4.38]]
Matrix product by vector:
[[0.]
 [0.]]


## Завдання 12

Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [112]:
matrix1 = np.random.randint(1, 11, size=(7, 7))
matrix2 = np.random.randint(1, 11, size=(7, 7))

difference = matrix1 - matrix2

print("Matrix 1 (7x7):\n", matrix1)
print("Matrix 2 (7x7):\n", matrix2)
print("(Matrix 1 - Matrix 2):\n", difference)

Matrix 1 (7x7):
 [[ 5  2  4  4 10  3  6]
 [ 3  4  6  8  3  8  2]
 [ 7  6  1  1  4  2 10]
 [10  7  7  8  9  9  8]
 [ 1  9  7  9 10  9  4]
 [ 7  2  8  5 10  3  1]
 [ 9  3  8  9  5  5  2]]
Matrix 2 (7x7):
 [[ 8  7 10  5  2  6 10]
 [ 8  2  4  6  8  4  7]
 [ 7  8 10  2 10  7  1]
 [ 4  9  5  2  5  6  1]
 [ 4  2  5  5  5  1  1]
 [ 9  5  7 10  4  4  3]
 [ 2  3  2  4  5  2  2]]
(Matrix 1 - Matrix 2):
 [[-3 -5 -6 -1  8 -3 -4]
 [-5  2  2  2 -5  4 -5]
 [ 0 -2 -9 -1 -6 -5  9]
 [ 6 -2  2  6  4  3  7]
 [-3  7  2  4  5  8  3]
 [-2 -3  1 -5  6 -1 -2]
 [ 7  0  6  5  0  3  0]]


## Завдання 13

Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть суму їх елементів

In [116]:
matrix1 = np.random.randint(-5, 6, size = (2, 2))
matrix2 = np.random.randint(-5, 6, size = (2, 2))

sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

print(f"Matrix 1:\n{matrix1}\n Matrix 2:\n{matrix2}")
print(f"Sum of all the elements of matrix 1:\n{sum_matrix1}")
print(f"Sum of all the elements of matrix 2:\n{sum_matrix2}")

Matrix 1:
[[ 1 -1]
 [ 2 -2]]
 Matrix 2:
[[ 0 -2]
 [ 1 -1]]
Sum of all the elements of matrix 1:
0
Sum of all the elements of matrix 2:
-2


## Завдання 14

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток елементів матриці, які менше за їх середнє арифметичне значення.

In [119]:
matrix = np.random.randint(1, 11, size=(3, 3))
mean_value = np.mean(matrix)
elements_less_than_mean = matrix[matrix < mean_value]
prod = np.prod(elements_less_than_mean)
print("Matrix (3x3):\n", matrix)
print("Mean value of matrix elements:", mean_value)
print("Elements less than mean value:", elements_less_than_mean)
print("Product of elements less than mean value:", prod)

Matrix (3x3):
 [[ 1  4  1]
 [ 4  7  2]
 [10  3 10]]
Mean value of matrix elements: 4.666666666666667
Elements less than mean value: [1 4 1 4 2 3]
Product of elements less than mean value: 96


## Завдання 15

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить найбільше ціле значення в кожному рядку матриці.

In [124]:
matrix = np.random.uniform(-1, 1, size=(3, 3))
round_matrix = np.round(matrix).astype(int)
max_in_rows = np.max(round_matrix, axis=1)
vector_column = max_in_rows.reshape(-1, 1)

print("Matrix (3x3):\n", matrix)
print("Rounded Matrix (with integers):\n", round_matrix)
print("Vector Column with the largest integer in each row:\n", vector_column)

Matrix (3x3):
 [[ 0.9   0.87 -0.11]
 [ 0.46  0.48 -0.39]
 [-0.76 -0.11 -0.22]]
Rounded Matrix (with integers):
 [[ 1  1  0]
 [ 0  0  0]
 [-1  0  0]]
Vector Column with the largest integer in each row:
 [[1]
 [0]
 [0]]


## Висновок

В лабораторній роботі було продемонстровано основні операції з матрицями та масивами у Python за допомогою бібліотеки NumPy, включаючи обчислення геометричних прогресій, роботу з дробовими частинами, математичні операції над матрицями та масивами, а також знаходження статистичних характеристик та обернених матриць.